Rb readmebuild
NSS-Therapeutic-Raccoons/WorkforceManagement pull request #24
Opened 2018-11-14 20:03 UTC by ricky-bruner

## Link to Ticket
Closes # [22](https://github.com/NSS-Therapeutic-Raccoons/WorkforceManagement/issues/22)

## Description of Proposed Changes
- Created README.md

## Steps to Test

Outline the steps to test

```sh
git fetch --all
git checkout rb-readmebuild
```

## Impacted Areas in Application

List general components of the application that this PR will affect:

* None.

## Mentions @username

@khardt
@figamus
@jeremiah3643
@ricky-bruner
@askingalot

## Definition of Done

1. Complete README that documents the steps to install the code, how to install any dependencies, or system configuration needed.

2018-11-14 21:58 UTC, askingalot requested changes
_Mostly_ a great readme, but there's one comment below...

2018-11-14 21:58 UTC, askingalot commented on README.md
> +3. Create a `Bangazon.db` file in the project.
This is not correct. The user needs to create a database using SSMS

2018-11-14 22:09 UTC, askingalot approved these changes

2018-11-15 15:03 UTC, Figamus approved these changes
Bada ba ba baaaaa. I'm loving it.

2018-11-15 15:43 UTC, merged